root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main -buildvcs=false ."
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  stop_on_error = true

[log]
  time = true

[screen]
  clear_on_rebuild = true
