version: '3.8'

services:
  # PostgreSQL Service
  db:
    image: postgres:13
    container_name: marketplace-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Go Service
  app:
    build: .
    container_name: shoto
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/marketplace?sslmode=disable
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend-network
    volumes:
      - .:/app
      - /app/tmp

networks:
  backend-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
